var shuffleSequence = seq("intro", "info", "list_ordering", sepWith("sep", anyOf("nounyverby")), "contact", "sr", "code");

var pastworkers = ["A105007VNA9G3C", "A14N0AMVXOBZYH", "A14SNQOYGXPZ7K", "A16AZHD3CCD77Q", "A175PJR0W3LO8I", "A1BNVR3EW5Y4HJ", "A1BQ6H1I73CWQY", "A1C0LX0PX3G45Y", "A1C0LX0PX3G45Y ", "A1DIL5CPN9GUU5", "A1E0EK09CA5OIO", "A1H35C5IAF8689", "A1JGFEO79YACUN", "A1JQS9AN8LEAKZ", "A1LFSWMIP0U8OH", "A1N3CDWENFR6B3", "A1QJSC1OUMZ1Y1", "A1RXP9JX7L40S2", "A1SL8OMT1OS77P", "A1UUPDVZS851IT", "A1WNHQEMEHNCPT", "A1Y25W1Y7KDE5", "A214DFHZ1PTVX2", "A21FEZLM4LN3TB", "A23TQCS8NU35CP", "A253Q11TZPQPIZ", "A25LRRAN2OC4I6", "A2BHIPGBZF902T", "A2BLGVW3OGZJVU", "A2II6DZ6VSNQBA", "A2JRWVPVWD1KAS", "A2LV5432PV1S39", "A2OBA0DHPPDLNX", "A2OBA0DHPPDLNX ", "A2OIFE4TAQ7AEI", "A2ZH5LDUY5UFD4", "A2ZY5OI9T2IFQK", "A32LYG2UEQ2PTR", "A32WFJGJ0VUKOO", "A35DS4T8H1MWYD", "A368ECVLBCK8X", "A37EDGVYCXGTC9", "A3A03S071WOD2C", "A3A03S071WOD2C ", "A3AENZ7D5M87JK", "A3AENZ7D5M87JX", "A3EJ3HW9OU8BNY", "A3JQT0NOQKDY6O", "A3K6HCRWJ6CGL1", "A3N3NSTEAB5S2K", "A3NND0D3AODSK2", "A3OZ8KF0HWSVWK", "A3S82OHUGFBR7L", "A3T7GZM21JXX68", "A3UFC2266HE6IY", "A3VWEX1IV75885", "A3W3EJGC73Z55", "A5D8FRODPHHDY", "A5D8FRODPHHDY ", "A911XMMVXT7IU", "A9U1PIVAC618J", "A9U1PIVAC618J ", "ACTW5YEWV9OR0", "ADDF4MCNSDE4W", "ADM5RFAZ3LWDF", "AGM91YL49ZBSH", "AHPR6M3OF0BMK", "AIG6UTA1PWMBE", "AIG6UTA1PWMBE ", "AQAXDL1INQC9Q", "ARBVAHQB82OE1", "AVAB6JJYQ1OIP", "AYEXVPS4R274L"];

var ds = "RegionedSentence";
var qs = "Question";
var sep = "Separator";

var manualSendResults = true;

var defaults = [
    "Separator", {
        transfer: 1500,
        errorMessage: "Wrong. Please wait for the next sentence",
        normalMessage: "Please wait for the next sentence" },
    "RegionedSentence", {
        mode: "self-paced reading" },
    "Question", {
        randomOrder: false,
        hasCorrect: true,
        as: ["Yes", "No"] }
];

var items = [
    ["sr", "__SendResults__", { }],
    ["sep", "Separator", {}],
    ["intro", "Message", {html: {include: "intro.html"}}],
    ["info", "Form", {html: {include: "info.html"},
        validators: {
            workerid: function(s) {if (pastworkers.indexOf(s) == -1) return true; else return "Sorry. You have already done a experiment in this series.";}
        }
    }],
    [["list_ordering", 0], "Separator", {transfer: 200, normalMessage: "The experiment will start momentarily"}],
    [["list_ordering", 0], "Separator", {transfer: 200, normalMessage: "The experiment will start momentarily"}],
    [["list_ordering", 0], "Separator", {transfer: 200, normalMessage: "The experiment will start momentarily"}],
    [["list_ordering", 0], "Separator", {transfer: 200, normalMessage: "The experiment will start momentarily"}],
    [["nounyverby",[1,0]], ds, {s: "The very cautious tourist followed the leader of the tour group.", id: "201", list: "1"},
        qs, {q: "Was the tourist cautious?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[1,0]], ds, {s: "The very cautious tourist followed the streets exactly as they appeared on the map.", id: "202", list: "2"},
        qs, {q: "Was the tourist take a street not on the map?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[1,0]], ds, {s: "The newly opened zoo received the tiger as a present from India.", id: "221", list: "3"},
        qs, {q: "Was the tiger from India?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[1,0]], ds, {s: "The newly opened zoo received the birds as a present from the benefactor.", id: "222", list: "4"},
        qs, {q: "Did the zoo buy the birds?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[2,0]], ds, {s: "The economically savvy businessman established the estate in the name of his mother.", id: "212", list: "1"},
        qs, {q: "Did the businessman establish an office building?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[2,0]], ds, {s: "The economically savvy businessman established the journal in hopes of making even more money.", id: "211", list: "2"},
        qs, {q: "Did the businessman hope to make more money?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[2,0]], ds, {s: "The respected university president persuaded the experts to rank the university even higher.", id: "272", list: "3"},
        qs, {q: "Did the experts rank the university higher?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[2,0]], ds, {s: "The respected university president persuaded the writer to publish the controversial novel.", id: "271", list: "4"},
        qs, {q: "Was the note uncontroversial?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[3,0]], ds, {s: "The group of friends discussed the scenes from the movie that they found most humorous.", id: "132", list: "1"},
        qs, {q: "Did the friends discuss the sad scenes?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[3,0]], ds, {s: "The group of friends discussed the movie that they had just gone to see.", id: "131", list: "2"},
        qs, {q: "Did the friends discuss a movie?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[3,0]], ds, {s: "The very angry man described the neighbor as a menace to society.", id: "121", list: "3"},
        qs, {q: "Did the man dislike his neighbor?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[3,0]], ds, {s: "The very angry man described the theft to the policeman soon after it had occurred.", id: "122", list: "4"},
        qs, {q: "Was the theft described long after it occurred?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[4,0]], ds, {s: "The world famous coach taught the bowler how to hold the ball.", id: "241", list: "1"},
        qs, {q: "Was the coach an amateur?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[4,0]], ds, {s: "The world famous coach taught the teams how to play the sport.", id: "242", list: "2"},
        qs, {q: "Wasthe coach world famous?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[4,0]], ds, {s: "The curious young boy saved the marble that he found on the playground.", id: "101", list: "3"},
        qs, {q: "Did the boy save something?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[4,0]], ds, {s: "The curious young boy saved the insect that he found in his backyard.", id: "102", list: "4"},
        qs, {q: "Was the insect found in a schoolyard?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[5,0]], ds, {s: "The quiet college student read the bible during times of intense stress.", id: "161", list: "1"},
        qs, {q: "Was the student talkative?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[5,0]], ds, {s: "The quiet college student read the text assigned by his history professor.", id: "162", list: "2"},
        qs, {q: "Was the student quiet?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[5,0]], ds, {s: "The world renowned scientist found the data from an old experiment.", id: "261", list: "3"},
        qs, {q: "Did the scientist fail to find the data?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[5,0]], ds, {s: "The world renowned scientist found the genes that are responsible for Parkinson's disease.", id: "262", list: "4"},
        qs, {q: "Did the scientist discover something?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[6,0]], ds, {s: "The terrible car accident blocked many drivers from the main entrance to the shopping mall.", id: "141", list: "1"},
        qs, {q: "Was the car accident terrible?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[6,0]], ds, {s: "The terrible car accident blocked many lanes of the town's only major highway.", id: "142", list: "2"},
        qs, {q: "Was the car accident very minor?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[6,0]], ds, {s: "The department store clerk accepted the gloves for return.", id: "252", list: "3"},
        qs, {q: "Did the clerk accept something for return?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[6,0]], ds, {s: "The department store clerk accepted the dollar from the shopper.", id: "251", list: "4"},
        qs, {q: "Did the clerk give the shopper a dollar?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[7,0]], ds, {s: "The very little girl imitated the infant as soon as it began to cry.", id: "112", list: "1"},
        qs, {q: "Did the girl imitate an old man?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[7,0]], ds, {s: "The very little girl imitated the laughter of the old woman with a tone of mockery.", id: "111", list: "2"},
        qs, {q: "Did the girl imitate laughter?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[7,0]], ds, {s: "The overly concerned parent visited the priest about his son.", id: "232", list: "3"},
        qs, {q: "Was the parent unconcerned?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[7,0]], ds, {s: "The overly concerned parent visited the teacher about his son.", id: "231", list: "4"},
        qs, {q: "Was the parent concerned?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[8,0]], ds, {s: "The moving company employees carried the chest from the van into the house.", id: "192", list: "1"},
        qs, {q: "Did the employees carry a chest?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[8,0]], ds, {s: "The moving company employees carried the sofa from the van into the house.", id: "191", list: "2"},
        qs, {q: "Did the employees carry a piano?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[8,0]], ds, {s: "The conservative political commentator criticized the airlines for not thoroughly screening all passenger bags.", id: "172", list: "3"},
        qs, {q: "Did the commentator criticize the airlines?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[8,0]], ds, {s: "The conservative political commentator criticized the lawyers for agreeing to defend the cold-blooded killer.", id: "171", list: "4"},
        qs, {q: "Did the commentator praise the lawyers?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[9,0]], ds, {s: "The company truck driver unloaded the cargo from his truck onto the loading dock.", id: "181", list: "1"},
        qs, {q: "Did the driver load something into his truck?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[9,0]], ds, {s: "The company truck driver unloaded the trunks from his truck into his client's office.", id: "182", list: "2"},
        qs, {q: "Did the driver unload something?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[9,0]], ds, {s: "The extremely generous woman bought her friends dinner in celebration of her promotion at work.", id: "152", list: "3"},
        qs, {q: "Did the woman buy dinner for her friends?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[9,0]], ds, {s: "The extremely generous woman bought her daughter many expensive gifts for her birthday.", id: "151", list: "4"},
        qs, {q: "Did the woman buy gifts for Christmas?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[10,0]], ds, {s: "The extremely generous woman bought her friends dinner in celebration of her promotion at work.", id: "152", list: "1"},
        qs, {q: "Did the woman buy dinner for her friends?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[10,0]], ds, {s: "The extremely generous woman bought her daughter many expensive gifts for her birthday.", id: "151", list: "2"},
        qs, {q: "Did the woman buy gifts for Christmas?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[10,0]], ds, {s: "The company truck driver unloaded the cargo from his truck onto the loading dock.", id: "181", list: "3"},
        qs, {q: "Did the driver load something into his truck?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[10,0]], ds, {s: "The company truck driver unloaded the trunks from his truck into his client's office.", id: "182", list: "4"},
        qs, {q: "Did the driver unload something?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[11,0]], ds, {s: "The conservative political commentator criticized the airlines for not thoroughly screening all passenger bags.", id: "172", list: "1"},
        qs, {q: "Did the commentator criticize the airlines?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[11,0]], ds, {s: "The conservative political commentator criticized the lawyers for agreeing to defend the cold-blooded killer.", id: "171", list: "2"},
        qs, {q: "Did the commentator praise the lawyers?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[11,0]], ds, {s: "The moving company employees carried the chest from the van into the house.", id: "192", list: "3"},
        qs, {q: "Did the employees carry a chest?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[11,0]], ds, {s: "The moving company employees carried the sofa from the van into the house.", id: "191", list: "4"},
        qs, {q: "Did the employees carry a piano?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[12,0]], ds, {s: "The overly concerned parent visited the priest about his son.", id: "232", list: "1"},
        qs, {q: "Was the parent unconcerned?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[12,0]], ds, {s: "The overly concerned parent visited the teacher about his son.", id: "231", list: "2"},
        qs, {q: "Was the parent concerned?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[12,0]], ds, {s: "The very little girl imitated the infant as soon as it began to cry.", id: "112", list: "3"},
        qs, {q: "Did the girl imitate an old man?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[12,0]], ds, {s: "The very little girl imitated the laughter of the old woman with a tone of mockery.", id: "111", list: "4"},
        qs, {q: "Did the girl imitate laughter?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[13,0]], ds, {s: "The department store clerk accepted the gloves for return.", id: "252", list: "1"},
        qs, {q: "Did the clerk accept something for return?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[13,0]], ds, {s: "The department store clerk accepted the dollar from the shopper.", id: "251", list: "2"},
        qs, {q: "Did the clerk give the shopper a dollar?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[13,0]], ds, {s: "The terrible car accident blocked many drivers from the main entrance to the shopping mall.", id: "141", list: "3"},
        qs, {q: "Was the car accident terrible?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[13,0]], ds, {s: "The terrible car accident blocked many lanes of the town's only major highway.", id: "142", list: "4"},
        qs, {q: "Was the car accident very minor?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[14,0]], ds, {s: "The world renowned scientist found the data from an old experiment.", id: "261", list: "1"},
        qs, {q: "Did the scientist fail to find the data?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[14,0]], ds, {s: "The world renowned scientist found the genes that are responsible for Parkinson's disease.", id: "262", list: "2"},
        qs, {q: "Did the scientist discover something?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[14,0]], ds, {s: "The quiet college student read the bible during times of intense stress.", id: "161", list: "3"},
        qs, {q: "Was the student talkative?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[14,0]], ds, {s: "The quiet college student read the text assigned by his history professor.", id: "162", list: "4"},
        qs, {q: "Was the student quiet?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[15,0]], ds, {s: "The curious young boy saved the marble that he found on the playground.", id: "101", list: "1"},
        qs, {q: "Did the boy save something?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[15,0]], ds, {s: "The curious young boy saved the insect that he found in his backyard.", id: "102", list: "2"},
        qs, {q: "Was the insect found in a schoolyard?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[15,0]], ds, {s: "The world famous coach taught the bowler how to hold the ball.", id: "241", list: "3"},
        qs, {q: "Was the coach an amateur?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[15,0]], ds, {s: "The world famous coach taught the teams how to play the sport.", id: "242", list: "4"},
        qs, {q: "Wasthe coach world famous?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[16,0]], ds, {s: "The very angry man described the neighbor as a menace to society.", id: "121", list: "1"},
        qs, {q: "Did the man dislike his neighbor?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[16,0]], ds, {s: "The very angry man described the theft to the policeman soon after it had occurred.", id: "122", list: "2"},
        qs, {q: "Was the theft described long after it occurred?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[16,0]], ds, {s: "The group of friends discussed the scenes from the movie that they found most humorous.", id: "132", list: "3"},
        qs, {q: "Did the friends discuss the sad scenes?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[16,0]], ds, {s: "The group of friends discussed the movie that they had just gone to see.", id: "131", list: "4"},
        qs, {q: "Did the friends discuss a movie?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[17,0]], ds, {s: "The respected university president persuaded the experts to rank the university even higher.", id: "272", list: "1"},
        qs, {q: "Did the experts rank the university higher?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[17,0]], ds, {s: "The respected university president persuaded the writer to publish the controversial novel.", id: "271", list: "2"},
        qs, {q: "Was the note uncontroversial?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[17,0]], ds, {s: "The economically savvy businessman established the estate in the name of his mother.", id: "212", list: "3"},
        qs, {q: "Did the businessman establish an office building?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[17,0]], ds, {s: "The economically savvy businessman established the journal in hopes of making even more money.", id: "211", list: "4"},
        qs, {q: "Did the businessman hope to make more money?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[18,0]], ds, {s: "The newly opened zoo received the tiger as a present from India.", id: "221", list: "1"},
        qs, {q: "Was the tiger from India?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[18,0]], ds, {s: "The newly opened zoo received the birds as a present from the benefactor.", id: "222", list: "2"},
        qs, {q: "Did the zoo buy the birds?", hasCorrect: "No", randomOrder: false}],
    [["nounyverby",[18,0]], ds, {s: "The very cautious tourist followed the leader of the tour group.", id: "201", list: "3"},
        qs, {q: "Was the tourist cautious?", hasCorrect: "Yes", randomOrder: false}],
    [["nounyverby",[18,0]], ds, {s: "The very cautious tourist followed the streets exactly as they appeared on the map.", id: "202", list: "4"},
        qs, {q: "Was the tourist take a street not on the map?", hasCorrect: "No", randomOrder: false}],
    ["contact", "Message", {consentRequired: false, html: {include: "contacts.html"}}],
    ["code", "Form", {consentRequired: false, continueMessage:"This is the final page. You do not need to click to continue.", html: {include: "code.html"}}]
];

